name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  devsecops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Static Analysis - CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # SCA - Dependency Check
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'DevSecOpsDemo'
          path: '.'

      # Build Docker Image
      - name: Build Docker image
        run: docker build -t devsecops-demo .

      # Scan Docker image - Trivy
      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-demo'
